[package]
name = "asm-8086"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
indoc = "2.0.5"
pretty_assertions = "1.4.0"

[lints.clippy]
unusual-byte-groupings = "allow"
# uninlined-format-args = { level = "allow", priority = 1 }
